'use strict';
// Replace this demo catalog with products from your actual supplier before launch.
const products=[
{id:1,name:'سماعة بلوتوث لاسلكية',cat:'إلكترونيات',price:649,old:899,rating:4.8,emoji:'🎧',tag:'الأكثر مبيعاً'},
{id:2,name:'ساعة ذكية رياضية',cat:'إلكترونيات',price:1199,old:1499,rating:4.7,emoji:'⌚',tag:'عرض خاص'},
{id:3,name:'شنطة ظهر عملية',cat:'لايف ستايل',price:799,old:999,rating:4.6,emoji:'🎒',tag:'جديد'},
{id:4,name:'مصباح مكتب عصري',cat:'المنزل',price:459,old:599,rating:4.5,emoji:'💡',tag:''},
{id:5,name:'كاميرا تصوير فورية',cat:'إلكترونيات',price:1899,old:2299,rating:4.9,emoji:'📷',tag:'مميز'},
{id:6,name:'زجاجة مياه حرارية',cat:'لايف ستايل',price:349,old:449,rating:4.6,emoji:'🥤',tag:''},
{id:7,name:'منظم مكتب متعدد',cat:'المنزل',price:299,old:399,rating:4.4,emoji:'🗂️',tag:''},
{id:8,name:'نظارة شمس عصرية',cat:'إكسسوارات',price:499,old:699,rating:4.7,emoji:'🕶️',tag:'خصم'},
{id:9,name:'حقيبة سفر صغيرة',cat:'لايف ستايل',price:1099,old:1399,rating:4.8,emoji:'🧳',tag:''},
{id:10,name:'ماوس لاسلكي مريح',cat:'إلكترونيات',price:399,old:529,rating:4.5,emoji:'🖱️',tag:''},
{id:11,name:'نبات ديكور منزلي',cat:'المنزل',price:259,old:349,rating:4.5,emoji:'🪴',tag:'جديد'},
{id:12,name:'محفظة جلد أنيقة',cat:'إكسسوارات',price:429,old:549,rating:4.6,emoji:'👛',tag:''}
];
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:0}).format(n)+' ج.م';
const safeRead=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let cart=safeRead('vindora_cart',{}),coupon=safeRead('vindora_coupon',''),category='الكل',query='';
const save=()=>{localStorage.setItem('vindora_cart',JSON.stringify(cart));localStorage.setItem('vindora_coupon',JSON.stringify(coupon))};
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3000)}
function renderCategories(){const cats=['الكل',...new Set(products.map(p=>p.cat))];$('#categories').innerHTML=cats.map(c=>`<button class="${c===category?'active':''}" data-category="${c}">${c}</button>`).join('')}
function renderProducts(){let items=products.filter(p=>(category==='الكل'||p.cat===category)&&`${p.name} ${p.cat}`.toLowerCase().includes(query.toLowerCase()));const sort=$('#sort').value;if(sort==='low')items.sort((a,b)=>a.price-b.price);if(sort==='high')items.sort((a,b)=>b.price-a.price);if(sort==='rating')items.sort((a,b)=>b.rating-a.rating);$('#resultCount').textContent=`${items.length} منتج`;$('#empty').hidden=items.length>0;$('#productGrid').innerHTML=items.map(p=>`<article class="product"><div class="product-image" role="img" aria-label="${p.name}">${p.emoji}${p.tag?`<span class="tag">${p.tag}</span>`:''}</div><div class="product-body"><span class="cat">${p.cat}</span><h3>${p.name}</h3><div class="rating">★ ${p.rating} <span>/ 5</span></div><div class="price"><strong>${money(p.price)}</strong><del>${money(p.old)}</del></div><button class="add" data-add="${p.id}">+ أضف للسلة</button></div></article>`).join('')}
function totals(){const subtotal=products.reduce((sum,p)=>sum+p.price*(cart[p.id]||0),0);const discount=coupon==='VINDORA10'?Math.round(subtotal*.1):0;const shipping=subtotal===0||subtotal>=1500?0:75;return{subtotal,discount,shipping,total:subtotal-discount+shipping,count:Object.values(cart).reduce((a,b)=>a+b,0)}}
function renderCart(){const t=totals();$('#cartCount').textContent=t.count;$('#drawerCount').textContent=`(${t.count})`;$('#cartItems').innerHTML=t.count?products.filter(p=>cart[p.id]>0).map(p=>`<div class="cart-row"><div class="cart-emoji">${p.emoji}</div><div class="cart-detail"><h4>${p.name}</h4><strong>${money(p.price)}</strong><div class="qty"><button aria-label="تقليل كمية ${p.name}" data-qty="${p.id}" data-delta="-1">−</button><span>${cart[p.id]}</span><button aria-label="زيادة كمية ${p.name}" data-qty="${p.id}" data-delta="1">+</button><button class="remove" data-remove="${p.id}">حذف</button></div></div></div>`).join(''):'<p class="empty">سلتك فاضية حالياً 🛒</p>';$('#subtotal').textContent=money(t.subtotal);$('#discount').textContent='− '+money(t.discount);$('#shipping').textContent=t.subtotal>=1500?'مجاني':money(t.shipping);$('#total').textContent=money(t.total);$('#checkoutBtn').disabled=!t.count;$('#coupon').value=coupon;$('#couponMsg').textContent=coupon==='VINDORA10'?'تم تفعيل خصم 10%':'';save()}
function add(id){cart[id]=(cart[id]||0)+1;renderCart();toast('تمت إضافة المنتج للسلة ✓')}
function openCart(){renderCart();$('#overlay').hidden=false;$('#cartDrawer').classList.add('open');$('#cartDrawer').setAttribute('aria-hidden','false');$('#closeCart').focus();document.body.style.overflow='hidden'}
function closeCart(){$('#overlay').hidden=true;$('#cartDrawer').classList.remove('open');$('#cartDrawer').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function openModal(html){closeCart();$('#modalContent').innerHTML=html;$('#modal').hidden=false;document.body.style.overflow='hidden';$('#closeModal').focus()}
function closeModal(){$('#modal').hidden=true;document.body.style.overflow=''}
const policies={shipping:['الشحن والتوصيل','هذه واجهة تجريبية. تكلفة الشحن الظاهرة تقديرية: 75 ج.م، ومجاناً عند وصول قيمة المنتجات إلى 1500 ج.م. قبل التشغيل الفعلي، حدّد مناطق التوصيل والمدة ورسوم الشحن مع شركة الشحن.'],returns:['الاستبدال والاسترجاع','قبل إطلاق المتجر، أضف سياسة استبدال واسترجاع مطابقة للقانون المعمول به، تشمل المدد والشروط وطريقة تقديم الطلب وتحمل تكاليف الشحن.'],privacy:['سياسة الخصوصية','يحفظ هذا النموذج محتويات السلة وكود الخصم محلياً في متصفحك. عند إرسال طلب تجريبي، تُحفظ بياناته محلياً على جهازك فقط، ولا تُرسل إلى خادم. قبل الإطلاق، أضف سياسة خصوصية فعلية وربطاً آمناً للطلبات.']};
function checkout(){if(!totals().count)return;const t=totals();openModal(`<h2 id="modalTitle">إتمام الطلب</h2><p class="muted">نموذج تجريبي — الطلب لا يُرسل إلى مورد أو شركة شحن.</p><form id="checkoutForm" class="checkout"><div class="two"><label>الاسم بالكامل<input name="name" required minlength="3" maxlength="100" autocomplete="name"></label><label>رقم الموبايل<input name="phone" type="tel" required pattern="[0-9+ ()-]{9,18}" title="أدخل رقم هاتف صحيح" autocomplete="tel"></label></div><label>البريد الإلكتروني<input name="email" type="email" required autocomplete="email"></label><div class="two"><label>المحافظة<input name="governorate" required maxlength="80"></label><label>المدينة / المنطقة<input name="city" required maxlength="80"></label></div><label>العنوان بالتفصيل<input name="address" required minlength="8" maxlength="250" autocomplete="street-address"></label><label>ملاحظات (اختياري)<input name="notes" maxlength="400"></label><label>طريقة الدفع<select name="payment"><option value="cash">الدفع عند الاستلام (تجريبي)</option></select></label><div class="total-line grand"><span>الإجمالي التقديري</span><b>${money(t.total)}</b></div><button class="primary full" type="submit">تأكيد الطلب التجريبي</button></form>`)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#categories').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;category=b.dataset.category;renderCategories();renderProducts()});$('#productGrid').addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(b)add(Number(b.dataset.add))});$('#search').addEventListener('input',e=>{query=e.target.value.trim();renderProducts()});$('#searchForm').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#products').scrollIntoView({behavior:'smooth'})});$('#sort').addEventListener('change',renderProducts);$('#cartBtn').addEventListener('click',openCart);$('#closeCart').addEventListener('click',closeCart);$('#overlay').addEventListener('click',closeCart);$('#cartItems').addEventListener('click',e=>{const q=e.target.closest('[data-qty]'),r=e.target.closest('[data-remove]');if(q){const id=Number(q.dataset.qty);cart[id]=Math.max(0,Math.min(99,(cart[id]||0)+Number(q.dataset.delta)));if(!cart[id])delete cart[id]}if(r)delete cart[Number(r.dataset.remove)];if(q||r)renderCart()});$('#applyCoupon').addEventListener('click',()=>{const val=$('#coupon').value.trim().toUpperCase();if(val==='VINDORA10'){coupon=val;toast('تم تفعيل الخصم')}else if(!val){coupon='';toast('تم حذف كود الخصم')}else{toast('كود الخصم غير صحيح');return}renderCart()});$('#checkoutBtn').addEventListener('click',checkout);$('#closeModal').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeCart()}});document.querySelectorAll('[data-modal]').forEach(b=>b.addEventListener('click',()=>{const [title,body]=policies[b.dataset.modal];openModal(`<h2 id="modalTitle">${title}</h2><p style="line-height:2">${body}</p>`)}));
$('#modalContent').addEventListener('submit',e=>{if(e.target.id!=='checkoutForm')return;e.preventDefault();const form=e.target,data=Object.fromEntries(new FormData(form)),t=totals(),order={id:'VD-'+Date.now().toString(36).toUpperCase(),date:new Date().toISOString(),customer:data,items:products.filter(p=>cart[p.id]).map(p=>({id:p.id,name:p.name,price:p.price,quantity:cart[p.id]})),...t,status:'تجريبي'};try{const orders=safeRead('vindora_demo_orders',[]);orders.push(order);localStorage.setItem('vindora_demo_orders',JSON.stringify(orders))}catch{toast('تعذر حفظ الطلب على هذا الجهاز');return}cart={};coupon='';renderCart();openModal(`<div style="text-align:center;padding:15px"><div style="font-size:65px">✅</div><h2 id="modalTitle">تم إنشاء الطلب التجريبي</h2><p>رقم الطلب: <b>${escapeHtml(order.id)}</b></p><p>الإجمالي: <b>${money(t.total)}</b></p><p class="muted">تم حفظ الطلب في متصفحك فقط. لن يُشحن أي منتج ولن تُحصّل أي مبالغ.</p><button id="done" class="primary">متابعة التسوق</button></div>`)});$('#modalContent').addEventListener('click',e=>{if(e.target.id==='done')closeModal()});$('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();toast('الاشتراك تجريبي؛ اربط خدمة بريد قبل النشر');e.target.reset()});$('#contactForm').addEventListener('submit',e=>{e.preventDefault();toast('النموذج تجريبي؛ لم تُرسل الرسالة');e.target.reset()});$('#year').textContent=new Date().getFullYear();renderCategories();renderProducts();renderCart();
